// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svblwefkzrlmebvveyrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2Ymx3ZWZrenJsbWVidnZleXJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDcxODAsImV4cCI6MjA2MTc4MzE4MH0.QCXfX7aM9F7DkaKV0gvKFStjYRqfPoLvgXdc33CgbDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);